// src/pages/PrivacyPolicyPage.jsx
// DPDP Act 2023-compliant privacy policy page.
// generatePrivacyPolicy is in src/lib/privacyPolicy.js

export { generatePrivacyPolicy } from "../lib/privacyPolicy";

export default function PrivacyPolicyPage({ clinic, doctor }) {
  const policy = generatePrivacyPolicy(clinic, doctor);

  const renderMarkdown = (content) => {
    return content.split("\n").map((line, i) => {
      if (line.startsWith("# "))  return <h1 key={i} style={{ fontFamily:"'DM Serif Display',serif", fontSize:32, color:"#0b2545", margin:"0 0 20px", lineHeight:1.2 }}>{line.replace("# ","")}</h1>;
      if (line.startsWith("## ")) return <h2 key={i} style={{ fontFamily:"'DM Serif Display',serif", fontSize:20, color:"#0b2545", margin:"32px 0 12px", borderBottom:"1px solid #dce8f5", paddingBottom:8 }}>{line.replace("## ","")}</h2>;
      if (line.startsWith("**") && line.endsWith("**") && !line.includes(" ")) return <p key={i} style={{ fontSize:14, fontWeight:700, color:"#0b2545", margin:"4px 0" }}>{line.slice(2,-2)}</p>;
      if (line.startsWith("- "))  return <div key={i} style={{ display:"flex", gap:8, marginBottom:6, paddingLeft:8 }}><span style={{ color:"#1565c0", flexShrink:0 }}>◦</span><span style={{ fontSize:14, color:"#334155", lineHeight:1.7 }}>{line.replace("- ","")}</span></div>;
      if (line.startsWith("---")) return <hr key={i} style={{ border:"none", borderTop:"1px solid #dce8f5", margin:"24px 0" }} />;
      if (line.startsWith("*") && line.endsWith("*")) return <p key={i} style={{ fontSize:12, color:"#94a3b8", fontStyle:"italic", lineHeight:1.6 }}>{line.slice(1,-1)}</p>;
      if (line.trim() === "")   return <div key={i} style={{ height:8 }} />;
      // Bold inline
      const parts = line.split(/\*\*(.*?)\*\*/g);
      return (
        <p key={i} style={{ fontSize:14, color:"#334155", lineHeight:1.8, marginBottom:2 }}>
          {parts.map((part, j) => j % 2 === 1 ? <strong key={j} style={{ color:"#0b2545" }}>{part}</strong> : part)}
        </p>
      );
    });
  };

  return (
    <div style={{ fontFamily:"'DM Sans',sans-serif", background:"white", minHeight:"100vh" }}>
      <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet"/>

      {/* Nav */}
      <div style={{ background:"white", borderBottom:"1px solid #dce8f5", padding:"16px 40px", display:"flex", alignItems:"center", justifyContent:"space-between" }}>
        <a href={`/${clinic?.slug}`} style={{ display:"flex", alignItems:"center", gap:10, textDecoration:"none" }}>
          <div style={{ width:30, height:30, borderRadius:8, background:"linear-gradient(135deg,#1565c0,#1e88e5)", display:"flex", alignItems:"center", justifyContent:"center", fontSize:14 }}>🦷</div>
          <span style={{ fontSize:14, fontWeight:700, color:"#0b2545" }}>{clinic?.name}</span>
        </a>
        <div style={{ display:"flex", gap:8, alignItems:"center" }}>
          <span style={{ fontSize:11, background:"rgba(34,197,94,0.1)", border:"1px solid rgba(34,197,94,0.2)", color:"#22c55e", borderRadius:6, padding:"3px 10px", fontFamily:"monospace" }}>
            DPDP Act 2023 Compliant
          </span>
          <a href={`/${clinic?.slug}`} style={{ fontSize:13, color:"#1565c0", textDecoration:"none", fontWeight:600 }}>← Back to Website</a>
        </div>
      </div>

      {/* Content */}
      <div style={{ maxWidth:760, margin:"0 auto", padding:"48px 40px 80px" }}>
        <div style={{ background:"#f0f7ff", border:"1px solid #dce8f5", borderRadius:12, padding:"16px 20px", marginBottom:32, display:"flex", gap:12, alignItems:"flex-start" }}>
          <span style={{ fontSize:20 }}>🔒</span>
          <div>
            <div style={{ fontSize:13, fontWeight:700, color:"#0b2545", marginBottom:4 }}>Your Data Rights Are Protected</div>
            <div style={{ fontSize:12, color:"#5a7a96", lineHeight:1.6 }}>
              This privacy policy is issued under the Digital Personal Data Protection Act, 2023 (India). It explains exactly what data we collect, why, and your rights. For questions, contact us at {clinic?.email || docEmail}.
            </div>
          </div>
        </div>
        {renderMarkdown(policy.content)}
        <div style={{ marginTop:40, padding:"16px 20px", background:"#f4f8fd", border:"1px solid #dce8f5", borderRadius:10, fontSize:11, color:"#94a3b8", fontFamily:"monospace", lineHeight:1.8 }}>
          Auto-generated by WaSpace · Version {policy.version} · {new Date(policy.generated_at).toLocaleDateString("en-IN")} · DPDP Act 2023 · DPDP Rules 2025
        </div>
      </div>
    </div>
  );
}
